-- feminist_data.lua v2
local M = {}

M.warn = {
  ["Bitch"]={level="implicit",alt=""},
  ["X姐"]={level="implicit",alt=""},
  ["三从四德"]={level="implicit",alt=""},
  ["三八"]={level="mild",alt="建议换种说法"},
  ["三八婆"]={level="implicit",alt=""},
  ["三十岁的老女人"]={level="implicit",alt=""},
  ["三寸金莲"]={level="implicit",alt=""},
  ["三陪小姐"]={level="implicit",alt=""},
  ["不下蛋的母鸡"]={level="implicit",alt=""},
  ["不守妇道"]={level="implicit",alt=""},
  ["不得好死"]={level="implicit",alt=""},
  ["不检点的女人"]={level="implicit",alt=""},
  ["丑八怪"]={level="implicit",alt=""},
  ["丑女"]={level="implicit",alt=""},
  ["中华田园女拳"]={level="implicit",alt=""},
  ["中年少女"]={level="implicit",alt=""},
  ["乳头"]={level="implicit",alt=""},
  ["乳房"]={level="implicit",alt=""},
  ["事业线"]={level="implicit",alt=""},
  ["事儿妈"]={level="mild",alt="建议换种说法"},
  ["二奶"]={level="mild",alt="建议换种说法"},
  ["二手货"]={level="severe",alt="建议用中性替代"},
  ["交际花"]={level="implicit",alt=""},
  ["人妖"]={level="implicit",alt=""},
  ["人尽可夫"]={level="severe",alt="建议用中性替代"},
  ["人渣"]={level="implicit",alt=""},
  ["人老珠黄"]={level="implicit",alt=""},
  ["从一而终"]={level="implicit",alt=""},
  ["他妈"]={level="implicit",alt=""},
  ["他妈的"]={level="implicit",alt=""},
  ["伏地魔/扶弟魔"]={level="implicit",alt=""},
  ["佛媛/病媛/支教媛"]={level="implicit",alt=""},
  ["你二大爷"]={level="implicit",alt=""},
  ["你他妈的"]={level="implicit",alt=""},
  ["你大爷的"]={level="implicit",alt=""},
  ["你奶奶的"]={level="implicit",alt=""},
  ["你妈"]={level="implicit",alt=""},
  ["你妈的"]={level="implicit",alt=""},
  ["你妈逼"]={level="implicit",alt=""},
  ["你妹"]={level="implicit",alt=""},
  ["你娘"]={level="implicit",alt=""},
  ["你老母"]={level="implicit",alt=""},
  ["你麻痹"]={level="implicit",alt=""},
  ["倚门卖笑"]={level="implicit",alt=""},
  ["倾城倾国"]={level="implicit",alt=""},
  ["假小子"]={level="mild",alt="建议换种说法"},
  ["做爱"]={level="implicit",alt=""},
  ["偷汉子"]={level="implicit",alt=""},
  ["傻屄"]={level="implicit",alt=""},
  ["傻比"]={level="implicit",alt=""},
  ["傻白甜"]={level="implicit",alt=""},
  ["傻逼"]={level="implicit",alt=""},
  ["克夫相"]={level="mild",alt="建议换种说法"},
  ["全家死光"]={level="implicit",alt=""},
  ["八婆"]={level="mild",alt="建议换种说法"},
  ["公交车"]={level="severe",alt="建议用中性替代"},
  ["公共汽车"]={level="severe",alt="建议用中性替代"},
  ["公道话"]={level="implicit",alt=""},
  ["内人"]={level="implicit",alt=""},
  ["内人/贱内/内子"]={level="implicit",alt=""},
  ["内当家"]={level="implicit",alt=""},
  ["军嫂/警嫂"]={level="implicit",alt=""},
  ["出轨女"]={level="implicit",alt=""},
  ["前台"]={level="implicit",alt=""},
  ["剩女"]={level="mild",alt="建议换种说法"},
  ["剩斗士"]={level="mild",alt="建议换种说法"},
  ["剩男"]={level="implicit",alt=""},
  ["剩货"]={level="implicit",alt=""},
  ["勾引"]={level="implicit",alt=""},
  ["勾搭"]={level="implicit",alt=""},
  ["卖淫女"]={level="implicit",alt=""},
  ["卧槽"]={level="implicit",alt=""},
  ["去妈味"]={level="implicit",alt=""},
  ["去死"]={level="implicit",alt=""},
  ["发情"]={level="implicit",alt=""},
  ["发浪"]={level="implicit",alt=""},
  ["发骚"]={level="implicit",alt=""},
  ["变态"]={level="implicit",alt=""},
  ["口交"]={level="implicit",alt=""},
  ["只生不养"]={level="implicit",alt=""},
  ["叫鸡/找鸡"]={level="implicit",alt=""},
  ["叶瘦花残"]={level="implicit",alt=""},
  ["吃屎"]={level="implicit",alt=""},
  ["吊带妹"]={level="implicit",alt=""},
  ["名媛"]={level="implicit",alt=""},
  ["名媛群"]={level="implicit",alt=""},
  ["名媛风/拼单名媛"]={level="implicit",alt=""},
  ["唯女子与小人难养也"]={level="implicit",alt=""},
  ["土包子"]={level="implicit",alt=""},
  ["圣母婊"]={level="mild",alt="建议换种说法"},
  ["圣母婊/白莲花"]={level="implicit",alt=""},
  ["坦克"]={level="severe",alt="建议用中性替代"},
  ["城市女"]={level="implicit",alt=""},
  ["堂客"]={level="implicit",alt=""},
  ["处女"]={level="implicit",alt=""},
  ["处女膜"]={level="implicit",alt=""},
  ["夜店咖"]={level="implicit",alt=""},
  ["大奶"]={level="implicit",alt=""},
  ["大奶/巨乳/豪乳"]={level="implicit",alt=""},
  ["大妈"]={level="mild",alt="建议换种说法"},
  ["大小姐脾气"]={level="implicit",alt=""},
  ["大波"]={level="implicit",alt=""},
  ["大鸡巴"]={level="implicit",alt=""},
  ["大龄产妇"]={level="implicit",alt=""},
  ["大龄剩女"]={level="implicit",alt=""},
  ["大龄未婚"]={level="implicit",alt=""},
  ["太平公主"]={level="mild",alt="建议换种说法"},
  ["太监"]={level="implicit",alt=""},
  ["夫唱妇随"]={level="implicit",alt=""},
  ["夫贵妻荣"]={level="implicit",alt=""},
  ["头发长见识短"]={level="implicit",alt=""},
  ["女主人"]={level="implicit",alt=""},
  ["女人心海底针"]={level="implicit",alt=""},
  ["女企业家"]={level="implicit",alt=""},
  ["女博士"]={level="implicit",alt=""},
  ["女司机"]={level="implicit",alt=""},
  ["女大不中留"]={level="implicit",alt=""},
  ["女子无才便是德"]={level="implicit",alt=""},
  ["女巫"]={level="implicit",alt=""},
  ["女强人"]={level="implicit",alt=""},
  ["女拳"]={level="implicit",alt=""},
  ["女拳师"]={level="implicit",alt=""},
  ["女权"]={level="implicit",alt=""},
  ["女汉子"]={level="implicit",alt=""},
  ["女流之辈"]={level="implicit",alt=""},
  ["女生拳"]={level="implicit",alt=""},
  ["女秘书"]={level="implicit",alt=""},
  ["女老板"]={level="implicit",alt=""},
  ["女里女气"]={level="implicit",alt=""},
  ["女领导"]={level="implicit",alt=""},
  ["女高管"]={level="implicit",alt=""},
  ["奶大无脑"]={level="implicit",alt=""},
  ["奶子"]={level="implicit",alt=""},
  ["好嫁风"]={level="mild",alt="建议换种说法"},
  ["好男不跟女斗"]={level="implicit",alt=""},
  ["如花"]={level="implicit",alt=""},
  ["妇人之仁"]={level="implicit",alt=""},
  ["妇人之见"]={level="implicit",alt=""},
  ["妇女"]={level="implicit",alt=""},
  ["妇孺皆知"]={level="implicit",alt=""},
  ["妈了个逼"]={level="implicit",alt=""},
  ["妈味"]={level="implicit",alt=""},
  ["妈宝女"]={level="implicit",alt=""},
  ["妈的"]={level="implicit",alt=""},
  ["妈虫"]={level="mild",alt="建议换种说法"},
  ["妈逼"]={level="implicit",alt=""},
  ["妒忌"]={level="implicit",alt=""},
  ["妓女"]={level="implicit",alt=""},
  ["妓女/娼妓/娼妇"]={level="implicit",alt=""},
  ["妖孽"]={level="implicit",alt=""},
  ["妖艳"]={level="implicit",alt=""},
  ["姘/姘头"]={level="implicit",alt=""},
  ["姘头"]={level="mild",alt="建议换种说法"},
  ["娇妻"]={level="mild",alt="建议换种说法"},
  ["娇妻文学/娇妻脑"]={level="implicit",alt=""},
  ["娘们"]={level="implicit",alt=""},
  ["娘们唧唧/女里女气"]={level="implicit",alt=""},
  ["娘娘腔"]={level="mild",alt="建议换种说法"},
  ["娘炮"]={level="mild",alt="建议换种说法"},
  ["婆娘/老婆子"]={level="implicit",alt=""},
  ["婆婆妈妈"]={level="implicit",alt=""},
  ["婊子"]={level="severe",alt="建议用中性替代"},
  ["婊子养的"]={level="severe",alt="建议用中性替代"},
  ["婚女"]={level="implicit",alt=""},
  ["婚奴"]={level="implicit",alt=""},
  ["婚驴"]={level="severe",alt="建议用中性替代"},
  ["媳妇熬成婆"]={level="implicit",alt=""},
  ["嫁出去的女儿泼出去的水"]={level="implicit",alt=""},
  ["嫁狗随狗"]={level="implicit",alt=""},
  ["嫁鸡随鸡"]={level="implicit",alt=""},
  ["嫉妒"]={level="implicit",alt=""},
  ["嫖娼"]={level="implicit",alt=""},
  ["嫖客"]={level="implicit",alt=""},
  ["孔雀女"]={level="implicit",alt=""},
  ["学渣妹"]={level="implicit",alt=""},
  ["宝妈"]={level="implicit",alt=""},
  ["寡妇"]={level="implicit",alt=""},
  ["小三"]={level="mild",alt="建议换种说法"},
  ["小三专业户"]={level="implicit",alt=""},
  ["小仙女"]={level="mild",alt="建议换种说法"},
  ["小作文"]={level="implicit",alt=""},
  ["小作文女王"]={level="implicit",alt=""},
  ["小公举"]={level="mild",alt="建议换种说法"},
  ["小姐"]={level="implicit",alt=""},
  ["小穴"]={level="implicit",alt=""},
  ["小蜜"]={level="implicit",alt=""},
  ["小骚货"]={level="implicit",alt=""},
  ["小鸡鸡"]={level="implicit",alt=""},
  ["少女感"]={level="mild",alt="建议换种说法"},
  ["尤物移人"]={level="implicit",alt=""},
  ["屁眼"]={level="implicit",alt=""},
  ["屌丝"]={level="implicit",alt=""},
  ["工具人"]={level="implicit",alt=""},
  ["巨乳"]={level="implicit",alt=""},
  ["师母/师娘"]={level="implicit",alt=""},
  ["干/操"]={level="implicit",alt=""},
  ["干/操/肏"]={level="implicit",alt=""},
  ["干你娘"]={level="severe",alt="建议用中性替代"},
  ["干你娘/操你妈"]={level="implicit",alt=""},
  ["废物"]={level="implicit",alt=""},
  ["废物/废柴"]={level="implicit",alt=""},
  ["弱智"]={level="implicit",alt=""},
  ["强奸"]={level="implicit",alt=""},
  ["徐娘半老"]={level="implicit",alt=""},
  ["心机女"]={level="mild",alt="建议换种说法"},
  ["心机婊"]={level="mild",alt="建议换种说法"},
  ["性交"]={level="implicit",alt=""},
  ["怨妇"]={level="mild",alt="建议换种说法"},
  ["总计"]={level="implicit",alt=""},
  ["恋爱脑"]={level="mild",alt="建议换种说法"},
  ["恐龙"]={level="implicit",alt=""},
  ["恶婆婆"]={level="implicit",alt=""},
  ["悍妇"]={level="mild",alt="建议换种说法"},
  ["情妇"]={level="mild",alt="建议换种说法"},
  ["情色"]={level="implicit",alt=""},
  ["成功男人背后都有一个女人"]={level="implicit",alt=""},
  ["成熟女人"]={level="implicit",alt=""},
  ["我操"]={level="implicit",alt=""},
  ["我操/我靠/我擦"]={level="implicit",alt=""},
  ["战利品"]={level="implicit",alt=""},
  ["手淫"]={level="implicit",alt=""},
  ["打拳"]={level="implicit",alt=""},
  ["打炮"]={level="implicit",alt=""},
  ["扫把星"]={level="mild",alt="建议换种说法"},
  ["抛头露面"]={level="implicit",alt=""},
  ["拜金女"]={level="mild",alt="建议换种说法"},
  ["拳师"]={level="implicit",alt=""},
  ["拼夕夕名媛"]={level="implicit",alt=""},
  ["捞女"]={level="mild",alt="建议换种说法"},
  ["排骨精"]={level="mild",alt="建议换种说法"},
  ["插足狂魔"]={level="implicit",alt=""},
  ["搓衣板"]={level="implicit",alt=""},
  ["摆拍媛"]={level="implicit",alt=""},
  ["摆设"]={level="implicit",alt=""},
  ["操你大爷/操你妹"]={level="implicit",alt=""},
  ["操你妈"]={level="severe",alt="建议用中性替代"},
  ["操你妈逼/操你妈屄"]={level="implicit",alt=""},
  ["操你娘"]={level="implicit",alt=""},
  ["操你祖宗/操你全家"]={level="implicit",alt=""},
  ["操翻/干翻"]={level="implicit",alt=""},
  ["放屁"]={level="implicit",alt=""},
  ["无孩爱猫女"]={level="implicit",alt=""},
  ["日你妈"]={level="severe",alt="建议用中性替代"},
  ["旺夫相"]={level="implicit",alt=""},
  ["普信女"]={level="implicit",alt=""},
  ["普信男"]={level="implicit",alt=""},
  ["智障"]={level="implicit",alt=""},
  ["更年期"]={level="mild",alt="建议换种说法"},
  ["更年期暴龙兽"]={level="implicit",alt=""},
  ["最毒妇人心"]={level="implicit",alt=""},
  ["最难消受美人恩"]={level="implicit",alt=""},
  ["月嫂"]={level="implicit",alt=""},
  ["月子"]={level="implicit",alt=""},
  ["月子病/月子仇"]={level="implicit",alt=""},
  ["月经怪"]={level="mild",alt="建议换种说法"},
  ["有病"]={level="implicit",alt=""},
  ["未亡人"]={level="implicit",alt=""},
  ["杂种"]={level="implicit",alt=""},
  ["死三八"]={level="implicit",alt=""},
  ["死全家"]={level="implicit",alt=""},
  ["死肥婆"]={level="severe",alt="建议用中性替代"},
  ["残花败柳"]={level="implicit",alt=""},
  ["母以子贵"]={level="implicit",alt=""},
  ["母兽"]={level="implicit",alt=""},
  ["母夜叉"]={level="severe",alt="建议用中性替代"},
  ["母大虫"]={level="severe",alt="建议用中性替代"},
  ["母牛"]={level="implicit",alt=""},
  ["母狗"]={level="severe",alt="建议用中性替代"},
  ["母猪"]={level="severe",alt="建议用中性替代"},
  ["母畜"]={level="implicit",alt=""},
  ["母老虎"]={level="severe",alt="建议用中性替代"},
  ["母驴"]={level="implicit",alt=""},
  ["母鸡"]={level="implicit",alt=""},
  ["水性杨花"]={level="implicit",alt=""},
  ["水桶腰"]={level="mild",alt="建议换种说法"},
  ["汉子茶"]={level="mild",alt="建议换种说法"},
  ["没教养"]={level="implicit",alt=""},
  ["河东狮吼"]={level="implicit",alt=""},
  ["泼妇"]={level="mild",alt="建议换种说法"},
  ["淫乱"]={level="implicit",alt=""},
  ["淫妇"]={level="implicit",alt=""},
  ["淫秽"]={level="implicit",alt=""},
  ["淫荡"]={level="implicit",alt=""},
  ["添头/搭头"]={level="implicit",alt=""},
  ["漂亮女人/美女"]={level="implicit",alt=""},
  ["潜规则"]={level="implicit",alt=""},
  ["灭绝师太"]={level="implicit",alt=""},
  ["炮架"]={level="severe",alt="建议用中性替代"},
  ["牝鸡司旦"]={level="implicit",alt=""},
  ["牝鸡司晨"]={level="implicit",alt=""},
  ["物质女"]={level="mild",alt="建议换种说法"},
  ["物质妹"]={level="implicit",alt=""},
  ["特么"]={level="implicit",alt=""},
  ["狐狸精"]={level="mild",alt="建议换种说法"},
  ["狗娘养的"]={level="implicit",alt=""},
  ["狗屁"]={level="implicit",alt=""},
  ["狗日"]={level="implicit",alt=""},
  ["狗日的"]={level="implicit",alt=""},
  ["狗杂种"]={level="implicit",alt=""},
  ["狗逼"]={level="implicit",alt=""},
  ["猪/猪婆"]={level="implicit",alt=""},
  ["猴子"]={level="implicit",alt=""},
  ["王八蛋"]={level="implicit",alt=""},
  ["生了孩子就不值钱了"]={level="implicit",alt=""},
  ["生育机器"]={level="mild",alt="建议换种说法"},
  ["甩手掌柜"]={level="implicit",alt=""},
  ["田园女权"]={level="implicit",alt=""},
  ["男主外女主内"]={level="implicit",alt=""},
  ["男人婆"]={level="mild",alt="建议换种说法"},
  ["男唱女随"]={level="implicit",alt=""},
  ["男妓"]={level="implicit",alt=""},
  ["男娼"]={level="implicit",alt=""},
  ["男子汉大丈夫不跟女人计较"]={level="implicit",alt=""},
  ["男尊女卑"]={level="implicit",alt=""},
  ["男才女貌"]={level="implicit",alt=""},
  ["男耕女织"]={level="implicit",alt=""},
  ["疯婆子"]={level="implicit",alt=""},
  ["疯子"]={level="implicit",alt=""},
  ["白嫖"]={level="mild",alt="建议换种说法"},
  ["白富美"]={level="implicit",alt=""},
  ["白痴"]={level="implicit",alt=""},
  ["白莲花"]={level="mild",alt="建议换种说法"},
  ["直男癌"]={level="implicit",alt=""},
  ["相夫教子"]={level="implicit",alt=""},
  ["矮冬瓜"]={level="implicit",alt=""},
  ["矮穷矬"]={level="implicit",alt=""},
  ["破处/开苞"]={level="implicit",alt=""},
  ["破鞋"]={level="severe",alt="建议用中性替代"},
  ["碎嘴婆"]={level="implicit",alt=""},
  ["神经婆"]={level="implicit",alt=""},
  ["神经病"]={level="implicit",alt=""},
  ["祸国殃民"]={level="implicit",alt=""},
  ["祸水"]={level="implicit",alt=""},
  ["秋扇见捐"]={level="implicit",alt=""},
  ["程序媛"]={level="implicit",alt=""},
  ["穷屌丝"]={level="implicit",alt=""},
  ["穷鬼"]={level="implicit",alt=""},
  ["穿过的鞋"]={level="implicit",alt=""},
  ["竹竿"]={level="implicit",alt=""},
  ["管家婆"]={level="mild",alt="建议换种说法"},
  ["粉木耳"]={level="severe",alt="建议用中性替代"},
  ["红颜祸水"]={level="implicit",alt=""},
  ["红颜薄命"]={level="implicit",alt=""},
  ["约炮"]={level="mild",alt="建议换种说法"},
  ["绝经的女人"]={level="implicit",alt=""},
  ["绿茶婊"]={level="mild",alt="建议换种说法"},
  ["缺席的妈妈"]={level="implicit",alt=""},
  ["美女工程师/美女医生"]={level="implicit",alt=""},
  ["老光棍"]={level="implicit",alt=""},
  ["老处女"]={level="mild",alt="建议换种说法"},
  ["老女人"]={level="mild",alt="建议换种说法"},
  ["老奶奶"]={level="implicit",alt=""},
  ["老妈子"]={level="implicit",alt=""},
  ["老妖婆"]={level="mild",alt="建议换种说法"},
  ["老姑婆"]={level="implicit",alt=""},
  ["老婆"]={level="implicit",alt=""},
  ["老巫婆"]={level="implicit",alt=""},
  ["老板娘"]={level="implicit",alt=""},
  ["老珠黄"]={level="implicit",alt=""},
  ["老阿姨"]={level="implicit",alt=""},
  ["肉便器"]={level="severe",alt="建议用中性替代"},
  ["肏你妈"]={level="severe",alt="建议用中性替代"},
  ["肏你祖宗十八代"]={level="implicit",alt=""},
  ["肚子不争气"]={level="implicit",alt=""},
  ["肛交"]={level="implicit",alt=""},
  ["肛门"]={level="implicit",alt=""},
  ["肥头大耳"]={level="implicit",alt=""},
  ["肥婆"]={level="mild",alt="建议换种说法"},
  ["胖妞"]={level="implicit",alt=""},
  ["胖子"]={level="implicit",alt=""},
  ["胖子/胖妞"]={level="implicit",alt=""},
  ["胸大无脑"]={level="implicit",alt=""},
  ["脑残"]={level="implicit",alt=""},
  ["自嗨女"]={level="implicit",alt=""},
  ["自慰"]={level="implicit",alt=""},
  ["臭娘们"]={level="implicit",alt=""},
  ["臭婊子"]={level="severe",alt="建议用中性替代"},
  ["色情"]={level="implicit",alt=""},
  ["花瓶"]={level="implicit",alt=""},
  ["荡妇"]={level="severe",alt="建议用中性替代"},
  ["蛇蝎女"]={level="mild",alt="建议换种说法"},
  ["螃蟹女"]={level="mild",alt="建议换种说法"},
  ["被操/被干"]={level="implicit",alt=""},
  ["装B"]={level="implicit",alt=""},
  ["装逼"]={level="implicit",alt=""},
  ["象腿"]={level="mild",alt="建议换种说法"},
  ["贤内助"]={level="implicit",alt=""},
  ["贤妻良母"]={level="implicit",alt=""},
  ["败犬"]={level="implicit",alt=""},
  ["贱人"]={level="implicit",alt=""},
  ["贱内"]={level="implicit",alt=""},
  ["贱比"]={level="implicit",alt=""},
  ["贱货"]={level="implicit",alt=""},
  ["贱逼"]={level="implicit",alt=""},
  ["赔钱货"]={level="severe",alt="建议用中性替代"},
  ["轮奸"]={level="implicit",alt=""},
  ["辣妹"]={level="implicit",alt=""},
  ["通奸"]={level="implicit",alt=""},
  ["遗孀"]={level="implicit",alt=""},
  ["酷坛子"]={level="implicit",alt=""},
  ["野鸡"]={level="severe",alt="建议用中性替代"},
  ["长舌妇"]={level="mild",alt="建议换种说法"},
  ["阳具"]={level="implicit",alt=""},
  ["阴唇"]={level="implicit",alt=""},
  ["阴户"]={level="implicit",alt=""},
  ["阴毛"]={level="implicit",alt=""},
  ["阴茎"]={level="implicit",alt=""},
  ["阴蒂"]={level="implicit",alt=""},
  ["阴道"]={level="implicit",alt=""},
  ["阴阳人"]={level="implicit",alt=""},
  ["露胸妹"]={level="implicit",alt=""},
  ["青蛙"]={level="implicit",alt=""},
  ["靠关系上位/睡上去的"]={level="implicit",alt=""},
  ["鞋弓袜小"]={level="implicit",alt=""},
  ["飞机场"]={level="mild",alt="建议换种说法"},
  ["飞机场/太平公主"]={level="implicit",alt=""},
  ["飞机杯"]={level="severe",alt="建议用中性替代"},
  ["马勒"]={level="implicit",alt=""},
  ["马子"]={level="severe",alt="建议用中性替代"},
  ["骚比"]={level="implicit",alt=""},
  ["骚货"]={level="severe",alt="建议用中性替代"},
  ["骚货/骚逼"]={level="implicit",alt=""},
  ["骚逼"]={level="severe",alt="建议用中性替代"},
  ["高龄产妇/高龄生育"]={level="implicit",alt=""},
  ["鸡/鸭"]={level="implicit",alt=""},
  ["鸡奸"]={level="implicit",alt=""},
  ["鸡巴"]={level="implicit",alt=""},
  ["麻子脸/麻婆"]={level="implicit",alt=""},
  ["黄脸婆"]={level="mild",alt="建议换种说法"},
  ["黄金剩斗士"]={level="implicit",alt=""},
  ["黑木耳"]={level="severe",alt="建议用中性替代"},
  ["黑逼"]={level="implicit",alt=""},
  ["齐天大剩"]={level="mild",alt="建议换种说法"},
  ["龟头"]={level="implicit",alt=""},
}

-- 教育模式：历史被污名化的字 → 原意说明
M.educate = {
  ["嫖"] = "'嫖'原意是轻捷勇猛——霍去病封'嫖姚校尉'，汉朝公主以'嫖'为名。明朝后才被曲解为召妓。",
  ["白嫖"] = "'嫖'原意是轻捷勇猛。'白嫖'用了被曲解后的贬义，建议用'白拿'。",
  ["妖"] = "'妖'在《说文》中解为'妍也'，原意是美丽、艳丽，和邪恶无关。",
  ["妖娆"] = "'妖'原意是美丽（《说文》：'妍也'），'妖娆'本义是娇艳美好。",
  ["嫉妒"] = "'嫉'和'妒'都是女字旁+贬义。民国有文人改成'男疾男户'来解构。",
  ["娇"] = "女字旁+'乔'（高），原意是妩媚、美好，不是贬义词。",
  ["媛"] = "'媛'在《尔雅》中为'美女'。2021年被污名化前，一直是褒义词。",
  ["名媛"] = "'媛'本指才女。2021年被污名化成'拼单名媛'，这是对女性的集体贬低。",
  ["妓"] = "'妓'原指歌舞艺人，汉代朝廷认证的文工团。和性无关。",
  ["伎"] = "同'妓'，原意是歌舞才艺女子。",
  ["媚"] = "'媚'在《诗经》中'媚兹一人'表爱慕，原意是喜爱，不是讨好。",
  ["佞"] = "'佞'原意是口才好、能言善辩，和女性无关。和'奸'一样被后来附会了性别贬义。",
  ["妄"] = "'妄'女字旁，原意是荒诞无理，并非特指女性的缺点。",
  ["娩"] = "'娩'女字旁+'免'，原意指妇女分娩。'免'有免除、解脱之意。",
  ["妻"] = "'妻'在甲骨文中是女子被抢婚的形象，反映了母系社会到父系社会的转变。",
  ["妾"] = "'妾'原意是女奴，后引申为侧室。一夫多妻制的语言残留。",
  ["奴婢"] = "'奴''婢'都是女字旁，反映了古代女性被奴役的社会现实。",
  ["婆婆"] = "'婆'女字旁+'波'，本义是年长女性。'婆婆妈妈'被用来贬低男性就是性别双标。",
  ["三八"] = "'三八'源自国际妇女节（3月8日），被污名化为骂人话是对妇女节的侮辱。反过来说'三八'就是女性力量。",
  ["妇女"] = "'妇女'是中性词。但被污名化成'妇女之见''妇人之仁'。其实'妇'=女+帚（持扫帚），指女性治理家务。",
  ["大妈"] = "'大妈'本是中性称呼，被污名化成'大妈广场舞''大妈抢黄金'。男性同样年龄不会用贬义称呼。",
  ["女司机"] = "数据显示男性交通事故率高于女性。'女司机'是被污名化的刻板印象。",
  ["娘"] = "'娘'原意是母亲、年轻女性。'娘娘腔''娘炮'是用'娘'来贬低男性，本质是厌女。",
  ["母"] = "'母'在甲骨文中是哺乳的女性形象。上古八大姓（姜姬嬴姒妘妫姚姞）全是女字旁。",
  ["老板娘"] = "《现代汉语词典》释义='老板的妻子'，默认女性是附属于丈夫。建议用'主理人''创始人'。",
  ["女强人"] = "'强人'不需要加'女'，男性事业成功不会叫'男强人'。",
  ["女博士"] = "'女博士'被污名为'第三类人'。博士不需要加性别前缀。",
  ["剩女"] = "'剩'字暗示女性是被挑选的。对应男性叫'钻石王老五'。双标明显。",
}

-- 新造词推荐：打旧词时推荐新词
M.new_word = {
  ["好屌"] = {recommend = "好蒂", reason = "用女性器官替代男性器官做感叹词"},
  ["嫉妒"] = {recommend = "男疾男戸", reason = "女字旁贬义改成男字旁"},
  ["婆婆妈妈"] = {recommend = "公公爹爹", reason = "用男性亲属替代女性亲属"},
  ["公道话"] = {recommend = "母道话", reason = "'公'换成'母'"},
  ["他妈的"] = {recommend = "他爹的", reason = "攻击对象从母亲换成父亲"},
  ["操你妈"] = {recommend = "騸你爹", reason = "性侵动作换成阉割动作"},
  ["干你娘"] = {recommend = "騸你爹", reason = "同上"},
  ["干"] = {recommend = "騸", reason = "性侵动词改成阉割动词"},
  ["操"] = {recommend = "騸", reason = "同上"},
  ["辣妹"] = {recommend = "辣弟", reason = "形容词加在男性身上"},
  ["大小姐脾气"] = {recommend = "大少爷脾气", reason = "行为互换，性别互换"},
  ["媳妇熬成婆"] = {recommend = "赘婿熬成爷", reason = "揭示传统叙事的压迫性"},
  ["月嫂"] = {recommend = "日叔", reason = "阿喵母系社会性转"},
  ["月子"] = {recommend = "日子（坐日子）", reason = "阿喵母系社会性转"},
  ["婆家"] = {recommend = "公家", reason = "母系社会性转"},
  ["水性杨花"] = {recommend = "水性杨草", reason = "把'花'改'草'解构"},
  ["胸罩"] = {recommend = "喉结罩", reason = "性转运动核心梗"},
  ["好闺蜜"] = {recommend = "好闺基", reason = "阿喵系列性转梗"},
}

-- 双标对照表：同一行为·男女不同词
M.double_standard = {
  ["风流"] = "↔ 女性对应：水性杨花（同样的事，男的叫风流，女的叫放荡）",
  ["花花公子"] = "↔ 女性对应：荡妇/破鞋（同样的事，男的有专属词，女的只有脏话）",
  ["钻石王老五"] = "↔ 女性对应：剩女/败犬（同样单身，男的是香饽饽，女的是没人要）",
  ["黄金单身汉"] = "↔ 女性对应：老处女（单身汉=潇洒，单身女=可怜）",
  ["有魄力"] = "↔ 女性对应：泼妇/母老虎（同样强势，换个性别就是骂人话）",
  ["有领导力"] = "↔ 女性对应：悍妇/母夜叉（男性=领导力，女性=凶悍）",
  ["健谈"] = "↔ 女性对应：长舌妇/八婆（话多，男的是健谈，女的是八卦）",
  ["人脉广"] = "↔ 女性对应：交际花（社交，男的是能力，女的是轻浮）",
  ["直性子"] = "↔ 女性对应：更年期/情绪化（同样脾气直，男的是率真，女的是有病）",
  ["应酬"] = "↔ 女性对应：败家（花钱，男的是工作应酬，女的是乱花钱）",
  ["男人不坏女人不爱"] = "↔ 女性对应：不检点/放荡（同样不守规矩，男的有魅力，女的有罪）",
  ["阅历丰富"] = "↔ 女性对应：二手货/穿过的鞋（有经历，男的是资本，女的是贬值）",
  ["风流倜傥"] = "↔ 女性对应：水性杨花（成语都是男的正面女的负面）",
  ["妻妾成群"] = "↔ 不存在（男的拥有多个伴侣=有权有势）",
  ["钻石王老五"] = "↔ 女性对应：剩女（年龄大，男的是黄金，女的是问题）",
}

-- 夸奖陷阱：表面夸实则束缚
M.praise_trap = {
  ["贤惠"] = "⚠ '贤'=女+臣跪下拿针，原意是服务于家庭才是美德。夸奖的同时也在设限",
  ["贤妻良母"] = "⚠ 对女性的最高评价=做好妻子和母亲。没有'贤夫良父'",
  ["乖"] = "⚠ 服从性测试用词。女性听话=好，不听话=不乖",
  ["懂事"] = "⚠ 同上，要求女性压抑自我需求来'懂事'",
  ["女中豪杰"] = "⚠ 最高夸奖=像男人，暗示女性默认是弱的",
  ["素颜女神"] = "⚠ 看似夸素颜，但'女神'的本质还是外貌打分",
  ["天生丽质"] = "⚠ 只用于女性，男性很少被夸'丽质'。把女性价值绑定在外貌上",
  ["出得厅堂入得厨房"] = "⚠ 对女性的全能要求，同时要求社交能力+家务能力",
  ["像男人一样优秀"] = "⚠ 为什么不能'像女人一样优秀'？默认女性不如男性",
  ["巾帼不让须眉"] = "⚠ 女性赢=像男性一样好，不是女性本身就好",
  ["宜室宜家"] = "⚠ 女性的价值在'适合结婚过日子'",
  ["端庄大方"] = "⚠ 要求女性行为得体，是束缚不是夸奖",
  ["有女人味"] = "⚠ '女人味'=温柔顺从才是女人，不符合=不像女人",
  ["上得厅堂下得厨房"] = "⚠ 对女性的全能期待，男性没有这个要求",
}

-- 控制性语言/关系中的隐形束缚
M.control_lang = {
  ["听话"] = "⚠ 注意：默认女性是'被管控'的对象。试试用'商量''一起决定'",
  ["乖"] = "⚠ 注意：对成年人用'乖'是一种俯视。试试用'好的''没问题'",
  ["女生不要太强势"] = "⚠ 注意：这是限制女性表达的典型话术。换成'坚持自己的观点'",
  ["女人就应该..."] = "⚠ 注意：'应该'=规范限定。没有任何事情是'女人就应该'做的",
  ["你一个女的懂什么"] = "⚠ 注意：这是能力否定。用性别否定一个人的专业判断",
  ["女孩子家家"] = "⚠ 注意：用'女孩子'来限制行为，暗示女性不应该做某些事",
  ["像个女孩子一样"] = "⚠ 注意：用女性特质作为贬低手段，本质是厌女",
  ["她比较情绪化"] = "⚠ 注意：把女性的合理情绪表达污名化。男性同样有情绪但不被这样说",
  ["女人心海底针"] = "⚠ 注意：把女性情感复杂化=神秘莫测，背后是'无法理解女性'的偏见",
  ["一哭二闹三上吊"] = "⚠ 注意：女性表达情绪的方式被污名化为撒泼。男性不会用这种归类",
  ["最毒妇人心"] = "⚠ 注意：成语级别的性别污名。直接把'毒'和'女性'绑定",
  ["头发长见识短"] = "⚠ 注意：外貌特征和能力绑定。男性头发长却不会被这样说",
  ["胸大无脑"] = "⚠ 注意：外貌羞辱+能力否定双杀",
  ["嫁出去的女儿泼出去的水"] = "⚠ 注意：把女儿视为可丢弃的财产",
}

return M